/*
 * SPDX-License-Identifier: MIT
 */

import { Schema, Types, model, type Document } from 'mongoose';

export interface PurchaseOrderItem {
  part: Types.ObjectId;
  quantity: number;
  unitCost?: number;
}

export interface PurchaseOrderDocument extends Document {
  tenantId: Types.ObjectId;
  siteId?: Types.ObjectId;
  vendor: Types.ObjectId;
  status: 'draft' | 'submitted' | 'acknowledged' | 'received';
  items: PurchaseOrderItem[];
  notes?: string;
  expectedDate?: Date;
  autoGenerated: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

const purchaseOrderSchema = new Schema<PurchaseOrderDocument>(
  {
    tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
    siteId: { type: Schema.Types.ObjectId, ref: 'Site', index: true },
    vendor: { type: Schema.Types.ObjectId, ref: 'InventoryVendor', required: true },
    status: {
      type: String,
      enum: ['draft', 'submitted', 'acknowledged', 'received'],
      default: 'draft',
    },
    items: [
      {
        part: { type: Schema.Types.ObjectId, ref: 'InventoryPart', required: true },
        quantity: { type: Number, required: true },
        unitCost: { type: Number },
      },
    ],
    notes: String,
    expectedDate: Date,
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true },
);

purchaseOrderSchema.index({ tenantId: 1, createdAt: -1 });

export default model<PurchaseOrderDocument>('InventoryPurchaseOrder', purchaseOrderSchema);
