/*
 * SPDX-License-Identifier: MIT
 */

import { Schema, Types, model, type Document } from 'mongoose';

export interface PurchaseOrderItem {
  part: Types.ObjectId;
  quantity: number;
  unitCost?: number | undefined;
  qtyReceived?: number | undefined;
}

export interface PurchaseOrderDocument extends Document {
  tenantId: Types.ObjectId;
  siteId?: Types.ObjectId | undefined;
  poNumber?: string | undefined;
  vendor: Types.ObjectId;
  status: 'draft' | 'pending' | 'approved' | 'ordered' | 'received' | 'closed';
  items: PurchaseOrderItem[];
  notes?: string | undefined;
  expectedDate?: Date | undefined;
  autoGenerated: boolean;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
}

const purchaseOrderSchema = new Schema<PurchaseOrderDocument>(
  {
    tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
    siteId: { type: Schema.Types.ObjectId, ref: 'Site', index: true },
    poNumber: { type: String, index: true },
    vendor: { type: Schema.Types.ObjectId, ref: 'InventoryVendor', required: true },
    status: {
      type: String,
      enum: ['draft', 'pending', 'approved', 'ordered', 'received', 'closed'],
      default: 'draft',
    },
    items: [
      {
        part: { type: Schema.Types.ObjectId, ref: 'InventoryPart', required: true },
        quantity: { type: Number, required: true },
        unitCost: { type: Number },
        qtyReceived: { type: Number, default: 0 },
      },
    ],
    notes: String,
    expectedDate: Date,
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true },
);

purchaseOrderSchema.index({ tenantId: 1, createdAt: -1 });

export default model<PurchaseOrderDocument>('InventoryPurchaseOrder', purchaseOrderSchema);
