/*
 * SPDX-License-Identifier: MIT
 */

import { z } from 'zod';

const objectId = z.string().min(1, 'Identifier is required');

export const partInputSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  partNo: z.string().optional(),
  description: z.string().optional(),
  category: z.string().optional(),
  sku: z.string().optional(),
  partNumber: z.string().optional(),
  location: z.string().optional(),
  quantity: z.number().optional(),
  unitCost: z.number().optional(),
  cost: z.number().optional(),
  unit: z.string().optional(),
  minStock: z.number().optional(),
  minQty: z.number().optional(),
  maxQty: z.number().optional(),
  reorderPoint: z.number().optional(),
  reorderQty: z.number().optional(),
  reorderThreshold: z.number().optional(),
  leadTime: z.number().optional(),
  autoReorder: z.boolean().optional(),
  vendorId: objectId.optional(),
  assetIds: z.array(objectId).optional(),
  pmTemplateIds: z.array(objectId).optional(),
  lastRestockDate: z.string().optional(),
  lastOrderDate: z.string().optional(),
  notes: z.string().optional(),
});

export const vendorInputSchema = z.object({
  name: z.string().min(1, 'Vendor name is required'),
  contactName: z.string().optional(),
  contactEmail: z.string().email().optional(),
  contactPhone: z.string().optional(),
  address: z.string().optional(),
  leadTimeDays: z.number().optional(),
  notes: z.string().optional(),
  preferredSkus: z.array(z.string()).optional(),
});

export const purchaseOrderInputSchema = z.object({
  vendorId: objectId,
  items: z
    .array(
      z.object({
        partId: objectId,
        quantity: z.number().positive('Quantity must be positive'),
        unitCost: z.number().optional(),
      }),
    )
    .min(1, 'At least one item is required'),
  notes: z.string().optional(),
  expectedDate: z.string().optional(),
  autoGenerated: z.boolean().optional(),
  poNumber: z.string().optional(),
});

export const locationInputSchema = z.object({
  name: z.string().min(1, 'Location name is required'),
  store: z.string().optional(),
  room: z.string().optional(),
  bin: z.string().optional(),
  parentId: objectId.optional(),
});

export const stockAdjustmentSchema = z.object({
  stockItemId: objectId,
  delta: z.number(),
  reason: z.string().optional(),
});

export const purchaseOrderStatusSchema = z.object({
  status: z.enum(['pending', 'approved', 'ordered', 'received', 'closed']),
  receipts: z
    .array(
      z.object({
        partId: objectId,
        quantity: z.number().nonnegative(),
      }),
    )
    .optional(),
});

export const inventoryTransferSchema = z.object({
  partId: objectId,
  fromLocationId: objectId,
  toLocationId: objectId,
  quantity: z.number().positive('Quantity must be greater than zero'),
});

export type PartInput = z.infer<typeof partInputSchema>;
export type VendorInput = z.infer<typeof vendorInputSchema>;
export type PurchaseOrderInput = z.infer<typeof purchaseOrderInputSchema>;
export type LocationInput = z.infer<typeof locationInputSchema>;
export type StockAdjustmentInput = z.infer<typeof stockAdjustmentSchema>;
export type PurchaseOrderStatusInput = z.infer<typeof purchaseOrderStatusSchema>;
export type InventoryTransferInput = z.infer<typeof inventoryTransferSchema>;
