/*
 * SPDX-License-Identifier: MIT
 */

import { z } from 'zod';

const objectId = z.string().min(1, 'Identifier is required');

export const partInputSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  description: z.string().optional(),
  category: z.string().optional(),
  sku: z.string().optional(),
  partNumber: z.string().optional(),
  location: z.string().optional(),
  quantity: z.number().optional(),
  unitCost: z.number().optional(),
  minStock: z.number().optional(),
  reorderPoint: z.number().optional(),
  reorderQty: z.number().optional(),
  reorderThreshold: z.number().optional(),
  autoReorder: z.boolean().optional(),
  vendorId: objectId.optional(),
  assetIds: z.array(objectId).optional(),
  pmTemplateIds: z.array(objectId).optional(),
  lastRestockDate: z.string().optional(),
  lastOrderDate: z.string().optional(),
  notes: z.string().optional(),
});

export const vendorInputSchema = z.object({
  name: z.string().min(1, 'Vendor name is required'),
  contactName: z.string().optional(),
  contactEmail: z.string().email().optional(),
  contactPhone: z.string().optional(),
  address: z.string().optional(),
  leadTimeDays: z.number().optional(),
  notes: z.string().optional(),
  preferredSkus: z.array(z.string()).optional(),
});

export const purchaseOrderInputSchema = z.object({
  vendorId: objectId,
  items: z
    .array(
      z.object({
        partId: objectId,
        quantity: z.number().positive('Quantity must be positive'),
        unitCost: z.number().optional(),
      }),
    )
    .min(1, 'At least one item is required'),
  notes: z.string().optional(),
  expectedDate: z.string().optional(),
  autoGenerated: z.boolean().optional(),
});

export type PartInput = z.infer<typeof partInputSchema>;
export type VendorInput = z.infer<typeof vendorInputSchema>;
export type PurchaseOrderInput = z.infer<typeof purchaseOrderInputSchema>;
