import express from 'express';
import { getAllConditionRules, getConditionRuleById, createConditionRule, updateConditionRule, deleteConditionRule, } from '../controllers/ConditionRuleController';
import { requireAuth } from '../middleware/authMiddleware';
import requireRole from '../middleware/requireRole';
import { validate } from '../middleware/validationMiddleware';
import { conditionRuleValidators } from '../validators/conditionRuleValidators';
const router = express.Router();
router.use(requireAuth);
router.get('/', getAllConditionRules);
router.get('/:id', getConditionRuleById);
router.post('/', requireRole('admin', 'manager'), conditionRuleValidators, validate, createConditionRule);
router.put('/:id', requireRole('admin', 'manager'), conditionRuleValidators, validate, updateConditionRule);
router.delete('/:id', requireRole('admin', 'manager'), deleteConditionRule);
export default router;
