import express from 'express';
import { requireAuth } from '../middleware/authMiddleware';
import requireRole from '../middleware/requireRole';
import { getAllRoles, getRoleById, createRole, updateRole, deleteRole, } from '../controllers/RoleController';
const router = express.Router();
router.use(requireAuth);
router.use(requireRole('admin'));
router.get('/', getAllRoles);
router.get('/:id', getRoleById);
router.post('/', createRole);
router.put('/:id', updateRole);
router.delete('/:id', deleteRole);
export default router;
