import express from 'express';
import { requireAuth } from '../middleware/authMiddleware';
import { getSummary, getAssetSummary, getWorkOrderSummary, getUpcomingMaintenance, getCriticalAlerts, } from '../controllers/SummaryController';
const router = express.Router();
router.get('/', requireAuth, getSummary);
router.get('/assets', requireAuth, getAssetSummary);
router.get('/workorders', requireAuth, getWorkOrderSummary);
router.get('/upcoming-maintenance', requireAuth, getUpcomingMaintenance);
router.get('/critical-alerts', requireAuth, getCriticalAlerts);
export default router;
