/*
 * SPDX-License-Identifier: MIT
 */

import { describe, it, beforeAll, afterAll, beforeEach, expect } from 'vitest';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';

import PartModel from '../src/modules/inventory/models/Part';
import VendorModel from '../src/modules/inventory/models/Vendor';
import PurchaseOrderModel from '../src/modules/inventory/models/PurchaseOrder';
import {
  listPurchaseOrders,
  exportPurchaseOrders,
  type InventoryContext,
} from '../src/modules/inventory/service';

let mongo: MongoMemoryServer;
let tenantId: string;
let tenantObjectId: mongoose.Types.ObjectId;
let context: InventoryContext;

beforeAll(async () => {
  mongo = await MongoMemoryServer.create({ binary: { version: '7.0.5' } });
  await mongoose.connect(mongo.getUri());
  tenantObjectId = new mongoose.Types.ObjectId();
  tenantId = tenantObjectId.toString();
  context = { tenantId };
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongo.stop();
});

beforeEach(async () => {
  await mongoose.connection.db.dropDatabase();
  const vendor = await VendorModel.create({ tenantId: tenantObjectId, name: 'Acme Manufacturing' });
  const part = await PartModel.create({
    tenantId: tenantObjectId,
    name: 'Bearing',
    quantity: 0,
    reorderPoint: 5,
    vendor: vendor._id,
  });
  await PurchaseOrderModel.create({
    tenantId: tenantObjectId,
    vendor: vendor._id,
    status: 'draft',
    autoGenerated: false,
    items: [{ part: part._id, quantity: 5, unitCost: 12 }],
  });
});

describe('Inventory purchase order exports', () => {
  it('lists purchase orders with vendor context', async () => {
    const orders = await listPurchaseOrders(context);
    expect(orders).toHaveLength(1);
    expect(orders[0].vendor?.name).toBe('Acme Manufacturing');
  });

  it('exports CSV data for ERP', async () => {
    const result = await exportPurchaseOrders(context, 'csv');
    expect(result.mimeType).toBe('text/csv');
    expect(result.filename).toMatch(/purchase-orders-\d+\.csv/);
    expect(result.buffer.toString('utf8')).toContain('Acme Manufacturing');
  });

  it('exports PDF files for ERP', async () => {
    const result = await exportPurchaseOrders(context, 'pdf');
    expect(result.mimeType).toBe('application/pdf');
    expect(result.filename).toMatch(/purchase-orders-\d+\.pdf/);
    expect(result.buffer.length).toBeGreaterThan(0);
  });
});
