import type { TenantScoped } from './http';

export interface InventoryItem extends TenantScoped {
  id: string;
  name: string;
  quantity: number;
  reorderThreshold?: number | undefined;
  reorderPoint?: number | undefined;
}

export interface InventoryUpdatePayload extends TenantScoped {
  _id: string;
  name: string;
  quantity: number;
}

export interface LinkedAsset {
  id: string;
  name: string;
}

export interface LinkedTemplate {
  id: string;
  title: string;
}

export interface PartAlertState {
  needsReorder: boolean;
  severity: 'ok' | 'warning' | 'critical';
  minimumLevel?: number | undefined;
}

export interface VendorSummary {
  id: string;
  name: string;
  contact?: string | undefined;
  contactName?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  address?: string | undefined;
  leadTimeDays?: number | undefined;
  notes?: string | undefined;
  preferredSkus?: string[] | undefined;
  partIds?: string[] | undefined;
}

export interface Part extends TenantScoped {
  id: string;
  qrCode?: string | undefined;
  commentsCount?: number | undefined;
  name: string;
  partNo?: string | undefined;
  description?: string | undefined;
  category?: string | undefined;
  sku?: string | undefined;
  partNumber?: string | undefined;
  location?: string | undefined;
  quantity: number;
  unitCost?: number | undefined;
  cost?: number | undefined;
  unit?: string | undefined;
  minStock?: number | undefined;
  minQty?: number | undefined;
  maxQty?: number | undefined;
  minLevel?: number | undefined;
  maxLevel?: number | undefined;
  reorderPoint: number;
  reorderQty?: number | undefined;
  reorderThreshold?: number | undefined;
  leadTime?: number | undefined;
  autoReorder?: boolean | undefined;
  vendorId?: string | undefined;
  vendor?: VendorSummary | undefined;
  assets?: LinkedAsset[] | undefined;
  pmTemplates?: LinkedTemplate[] | undefined;
  notes?: string | undefined;
  lastRestockDate?: string | undefined;
  lastOrderDate?: string | undefined;
  lastAutoReorderAt?: string | undefined;
  alertState?: PartAlertState | undefined;
  image?: string | undefined;
  attachments?: PartAttachment[] | undefined;
  attachmentsCount?: number | undefined;
  stockByLocation?: PartLocationStock[] | undefined;
}

export interface PartAttachment {
  id?: string | undefined;
  name?: string | undefined;
  url?: string | undefined;
  uploadedBy?: string | undefined;
  uploadedAt?: string | undefined;
}

export interface PurchaseOrderItemPayload {
  partId: string;
  quantity: number;
  unitCost?: number | undefined;
}

export interface PurchaseOrderPayload {
  vendorId: string;
  items: PurchaseOrderItemPayload[];
  notes?: string | undefined;
  expectedDate?: string | undefined;
  autoGenerated?: boolean | undefined;
  poNumber?: string | undefined;
}

export interface PurchaseOrderItem {
  partId: string;
  partName: string;
  quantity: number;
  unitCost?: number | undefined;
  qtyReceived?: number | undefined;
}

export interface PurchaseOrder extends TenantScoped {
  id: string;
  vendor?: VendorSummary | undefined;
  poNumber?: string | undefined;
  status: 'Draft' | 'Pending' | 'Approved' | 'Ordered' | 'Received' | 'Closed';
  autoGenerated: boolean;
  notes?: string | undefined;
  expectedDate?: string | undefined;
  createdAt: string;
  items: PurchaseOrderItem[];
}

export interface InventoryAlert extends TenantScoped {
  partId: string;
  partName: string;
  quantity: number;
  reorderPoint: number;
  minLevel?: number | undefined;
  vendorName?: string | undefined;
  assetNames: string[];
  pmTemplateTitles: string[];
  lastTriggeredAt?: string | undefined;
}

export interface InventoryLocation extends TenantScoped {
  id: string;
  siteId?: string | undefined;
  store: string;
  room?: string | undefined;
  bin?: string | undefined;
}

export interface StockItem extends TenantScoped {
  id: string;
  partId: string;
  part?: Pick<Part, 'id' | 'name' | 'partNumber' | 'partNo'> | undefined;
  locationId: string;
  location?: InventoryLocation | undefined;
  quantity: number;
  unitCost?: number | undefined;
  unit?: string | undefined;
  cost?: number | undefined;
}

export interface PartLocationStock {
  stockItemId: string;
  locationId: string;
  location?: InventoryLocation | undefined;
  quantity: number;
  unitCost?: number | undefined;
  unit?: string | undefined;
  cost?: number | undefined;
}

export interface StockAdjustment {
  stockItemId: string;
  partId: string;
  locationId: string;
  newQuantity: number;
  reason?: string | undefined;
  location?: InventoryLocation | undefined;
}

export interface StockHistoryEntry {
  id: string;
  partId: string;
  stockItemId: string;
  delta: number;
  reason?: string | undefined;
  createdAt: string | Date;
  location: {
    locationId: string;
    store?: string | undefined;
    room?: string | undefined;
    bin?: string | undefined;
  };
}

export interface InventoryTransfer extends TenantScoped {
  id: string;
  partId: string;
  fromLocationId: string;
  toLocationId: string;
  quantity: number;
  createdAt: string;
  createdBy?: string | undefined;
}

export interface InventoryTransferPayload {
  partId: string;
  fromLocationId: string;
  toLocationId: string;
  quantity: number;
}

export interface PartUsageReportSummary {
  totalQuantity: number;
  totalCost: number;
  distinctParts: number;
  workOrders: number;
}

export interface PartUsageReportItem {
  partId: string;
  partName: string;
  partNumber?: string | undefined;
  totalQuantity: number;
  totalCost: number;
  workOrderCount: number;
  lastUsedAt?: string | undefined;
  unitCost?: number | undefined;
}

export interface PartUsageReport {
  summary: PartUsageReportSummary;
  parts: PartUsageReportItem[];
}
