export interface InventoryItem {
  id: string;
  tenantId?: string;
  siteId?: string;
  name: string;
  quantity: number;
  reorderThreshold?: number;
  reorderPoint?: number;
}

export interface InventoryUpdatePayload {
  _id: string;
  tenantId?: string;
  siteId?: string;
  name: string;
  quantity: number;
}

export interface LinkedAsset {
  id: string;
  name: string;
}

export interface LinkedTemplate {
  id: string;
  title: string;
}

export interface PartAlertState {
  needsReorder: boolean;
  severity: 'ok' | 'warning' | 'critical';
}

export interface VendorSummary {
  id: string;
  name: string;
  contact?: string;
  contactName?: string;
  email?: string;
  phone?: string;
  address?: string;
  leadTimeDays?: number;
  notes?: string;
  preferredSkus?: string[];
  partIds?: string[];
}

export interface Part {
  id: string;
  tenantId: string;
  siteId?: string;
  name: string;
  partNo?: string;
  description?: string;
  category?: string;
  sku?: string;
  partNumber?: string;
  location?: string;
  quantity: number;
  unitCost?: number;
  cost?: number;
  unit?: string;
  minStock?: number;
  minQty?: number;
  maxQty?: number;
  reorderPoint: number;
  reorderQty?: number;
  reorderThreshold?: number;
  leadTime?: number;
  autoReorder?: boolean;
  vendorId?: string;
  vendor?: VendorSummary;
  assets?: LinkedAsset[];
  pmTemplates?: LinkedTemplate[];
  notes?: string;
  lastRestockDate?: string;
  lastOrderDate?: string;
  lastAutoReorderAt?: string;
  alertState?: PartAlertState;
  image?: string;
}

export interface PurchaseOrderItemPayload {
  partId: string;
  quantity: number;
  unitCost?: number;
}

export interface PurchaseOrderPayload {
  vendorId: string;
  items: PurchaseOrderItemPayload[];
  notes?: string;
  expectedDate?: string;
  autoGenerated?: boolean;
  poNumber?: string;
}

export interface PurchaseOrderItem {
  partId: string;
  partName: string;
  quantity: number;
  unitCost?: number;
  qtyReceived?: number;
}

export interface PurchaseOrder {
  id: string;
  tenantId?: string;
  siteId?: string;
  vendor?: VendorSummary;
  poNumber?: string;
  status: 'Draft' | 'Pending' | 'Approved' | 'Ordered' | 'Received' | 'Closed';
  autoGenerated: boolean;
  notes?: string;
  expectedDate?: string;
  createdAt: string;
  items: PurchaseOrderItem[];
}

export interface InventoryAlert {
  partId: string;
  partName: string;
  tenantId?: string;
  siteId?: string;
  quantity: number;
  reorderPoint: number;
  vendorName?: string;
  assetNames: string[];
  pmTemplateTitles: string[];
  lastTriggeredAt?: string;
}

export interface InventoryLocation {
  id: string;
  tenantId: string;
  siteId?: string;
  name: string;
  store?: string;
  room?: string;
  bin?: string;
  parentId?: string;
  path: string[];
}

export interface StockItem {
  id: string;
  tenantId: string;
  siteId?: string;
  partId: string;
  part?: Pick<Part, 'id' | 'name' | 'partNumber' | 'partNo'>;
  locationId: string;
  location?: InventoryLocation;
  quantity: number;
  unitCost?: number;
  unit?: string;
  cost?: number;
}

export interface StockAdjustment {
  stockItemId: string;
  partId: string;
  locationId: string;
  newQuantity: number;
  reason?: string;
  location?: InventoryLocation;
}

export interface StockHistoryEntry {
  id: string;
  partId: string;
  stockItemId: string;
  delta: number;
  reason?: string;
  createdAt?: string;
  location: {
    locationId: string;
    store?: string;
    room?: string;
    bin?: string;
  };
}
