export interface InventoryItem {
  id: string;
  tenantId?: string;
  siteId?: string;
  name: string;
  quantity: number;
  reorderThreshold?: number;
  reorderPoint?: number;
}

export interface InventoryUpdatePayload {
  _id: string;
  tenantId?: string;
  siteId?: string;
  name: string;
  quantity: number;
}

export interface LinkedAsset {
  id: string;
  name: string;
}

export interface LinkedTemplate {
  id: string;
  title: string;
}

export interface PartAlertState {
  needsReorder: boolean;
  severity: 'ok' | 'warning' | 'critical';
}

export interface VendorSummary {
  id: string;
  name: string;
  contact?: string;
  contactName?: string;
  email?: string;
  phone?: string;
  address?: string;
  leadTimeDays?: number;
  notes?: string;
  preferredSkus?: string[];
  partIds?: string[];
}

export interface Part {
  id: string;
  tenantId: string;
  siteId?: string;
  name: string;
  description?: string;
  category?: string;
  sku?: string;
  partNumber?: string;
  location?: string;
  quantity: number;
  unitCost?: number;
  minStock?: number;
  reorderPoint: number;
  reorderQty?: number;
  reorderThreshold?: number;
  autoReorder?: boolean;
  vendorId?: string;
  vendor?: VendorSummary;
  assets?: LinkedAsset[];
  pmTemplates?: LinkedTemplate[];
  notes?: string;
  lastRestockDate?: string;
  lastOrderDate?: string;
  lastAutoReorderAt?: string;
  alertState?: PartAlertState;
  image?: string;
}

export interface PurchaseOrderItemPayload {
  partId: string;
  quantity: number;
  unitCost?: number;
}

export interface PurchaseOrderPayload {
  vendorId: string;
  items: PurchaseOrderItemPayload[];
  notes?: string;
  expectedDate?: string;
  autoGenerated?: boolean;
}

export interface PurchaseOrderItem {
  partId: string;
  partName: string;
  quantity: number;
  unitCost?: number;
}

export interface PurchaseOrder {
  id: string;
  tenantId?: string;
  siteId?: string;
  vendor?: VendorSummary;
  status: 'draft' | 'submitted' | 'acknowledged' | 'received';
  autoGenerated: boolean;
  notes?: string;
  expectedDate?: string;
  createdAt: string;
  items: PurchaseOrderItem[];
}

export interface InventoryAlert {
  partId: string;
  partName: string;
  tenantId?: string;
  siteId?: string;
  quantity: number;
  reorderPoint: number;
  vendorName?: string;
  assetNames: string[];
  pmTemplateTitles: string[];
  lastTriggeredAt?: string;
}
